### PR TITLE
Update LocalDeploymentManager.cpp

### PR DESCRIPTION
**Pull request by m-samiec**
#### Description
Bad merge conflict fix

@oblm @aleximprobable

### CODE REVIEW

**Comment by oblm** [comment]
Before this PR my UE4.sln build failed with:

```
1>PROBLEM: C:\unreal\UnrealEngine\Engine\Plugins\UnrealGDK\SpatialGDK\Intermediate\Build\Win64\UE4Editor\Development\SpatialGDKServices\LocalDeploymentManager.cpp.obj
1>PROBLEM: C:\Users\claire\AppData\Local\Temp\.fbuild.tmp\0x00000000\core_1004\LocalDeploymentManager.cpp.obj
1>LocalDeploymentManager.cpp
1>C:\unreal\UnrealEngine\Engine\Plugins\UnrealGDK\SpatialGDK\Source\SpatialGDKServices\Private\LocalDeploymentManager.cpp(107): error C2084: function 'void FLocalDeploymentManager::SetInChina(bool)' already has a body
1>C:\unreal\UnrealEngine\Engine\Plugins\UnrealGDK\SpatialGDK\Source\SpatialGDKServices\Private\LocalDeploymentManager.cpp(101): note: see previous definition of 'SetInChina'
1>EXEC : Failed to build Object. error : 2 (0x02) Target: 'C:\Users\claire\AppData\Local\Temp\.fbuild.tmp\0x00000000\core_1004\LocalDeploymentManager.cpp.obj'
```

when I pull this fix I can no longer reproduce that failure.
